const groups=['咖啡与茶','本地小吃','路氹餐饮'];
document.getElementById('store-groups').innerHTML=groups.map(g=>`
  <div class="store-group">
    <h3>${g}</h3>
    <div class="store-grid">${shops.filter(s=>s.g===g).map(s=>`
      <a class="store" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.n+' 澳门')}">
        <span><strong>${s.n}${s.extra?'<i class="store-flag">另列分店</i>':''}</strong><small>${s.a} · 打开地图核对店址</small></span><em>↗</em>
      </a>`).join('')}</div>
  </div>`).join('');

const ox=atlas.origin[0],oy=atlas.origin[1],toWorld=(lon,lat)=>[(lon-ox)*103000,(lat-oy)*111000];route.forEach(s=>s.p=toWorld(s.lon,s.lat));hotel.p=toWorld(hotel.lon,hotel.lat);
const streets=atlas.roads.filter(r=>r[1].some(p=>p&&p[1]>700&&p[0]<1250));
const shores=atlas.coasts.filter(r=>r.some(p=>p&&p[1]>700&&p[0]<1250));
const buildings=atlas.buildings.map(b=>({p:b[0],h:b[1],y:b[0].reduce((a,q)=>a+q[1],0)/b[0].length})).filter(b=>b.y>700).sort((a,b)=>b.y-a.y);
let selected=1,stage='all';const canvas=document.getElementById('route-map'),ctx=canvas.getContext('2d');let W=0,H=0,dpr=1,angle=-.16,zoom=1,tilted=true,panX=0,panY=0,pending=0,hits=[],pointers=new Map(),tap=null,pinch=null;
const active=()=>stage==='all'?route:route.filter(s=>s.stage===Number(stage));
function camera(){const pts=active().map(s=>s.p);if(stage==='all')pts.push(hotel.p);let xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),center=[(xmin+xmax)/2,(ymin+ymax)/2];let dx=Math.max(700,xmax-xmin),dy=Math.max(640,ymax-ymin);return {center,scale:Math.min(W*.69/dx,H*.63/dy,.85)*zoom,tilt:tilted?.54:0}}
function project(p,z,C){let x=p[0]-C.center[0],y=p[1]-C.center[1],cs=Math.cos(angle),sn=Math.sin(angle),xr=x*cs-y*sn,yr=x*sn+y*cs,ct=Math.cos(C.tilt),st=Math.sin(C.tilt),f=4300/(4300+yr*st-z*ct);return [W/2+panX+xr*C.scale*f,H/2+panY-(yr*ct+z*st)*C.scale*f]}
function path(points,z,C){ctx.beginPath();let started=false;for(const p of points){if(!p){started=false;continue}let q=project(p,z,C);if(!started){ctx.moveTo(q[0],q[1]);started=true}else ctx.lineTo(q[0],q[1])}}
function markerLocation(q,used){const candidates=[[0,0],[0,-27],[27,0],[-27,0],[0,27],[26,-25],[-26,-25],[37,14],[-37,14],[0,-52],[50,-25],[-50,-25]];let best=q,bestScore=-1e9;for(const [dx,dy] of candidates){let x=q[0]+dx,y=q[1]+dy,closest=used.length?Math.min(...used.map(p=>Math.hypot(p[0]-x,p[1]-y))):100;let edge=Math.min(x-20,W-x-20,y-70,H-y-45);let score=Math.min(closest,38)-Math.hypot(dx,dy)*.22+(edge<0?edge*2:0);if(score>bestScore){bestScore=score;best=[x,y]}}used.push(best);return best}
function draw(){if(!W)return;const C=camera();ctx.setTransform(dpr,0,0,dpr,0,0);let bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#25505a');bg.addColorStop(1,'#0a2635');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
 for(const [r,p] of streets){path(p,0,C);ctx.lineWidth=r<2?Math.max(2.1,8*C.scale):r<4?Math.max(1.2,5*C.scale):Math.max(.65,2.5*C.scale);ctx.strokeStyle=r<3?'rgba(241,239,217,.23)':'rgba(212,225,208,.10)';ctx.stroke()}
 for(const p of shores){path(p,0,C);ctx.lineWidth=1.7;ctx.strokeStyle='rgba(122,220,221,.34)';ctx.stroke()}
 for(const b of buildings){let p=b.p;if(p.length<4)continue;let bottom=p.map(q=>project(q,0,C)),top=p.map(q=>project(q,b.h,C));for(let i=0;i<p.length-1;i++){ctx.beginPath();ctx.moveTo(bottom[i][0],bottom[i][1]);ctx.lineTo(bottom[i+1][0],bottom[i+1][1]);ctx.lineTo(top[i+1][0],top[i+1][1]);ctx.lineTo(top[i][0],top[i][1]);ctx.closePath();ctx.fillStyle=i%2?'rgba(80,124,122,.43)':'rgba(68,112,113,.52)';ctx.fill()}ctx.beginPath();top.forEach((q,i)=>i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1]));ctx.closePath();ctx.fillStyle='rgba(180,201,173,.34)';ctx.fill()}
 let seq=active();ctx.beginPath();seq.forEach((s,i)=>{let q=project(s.p,30,C);i?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])});ctx.strokeStyle='#c9eb86';ctx.globalAlpha=.22;ctx.lineWidth=11;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();ctx.globalAlpha=.95;ctx.setLineDash([7,5]);ctx.lineWidth=2.7;ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=1;
 hits=[];let used=[];for(const s of seq){let foot=project(s.p,0,C),origin=project(s.p,62,C),head=markerLocation(origin,used),isSelected=selected===s.id;ctx.strokeStyle='#c9eb86';ctx.globalAlpha=.72;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(foot[0],foot[1]);ctx.lineTo(head[0],head[1]);ctx.stroke();ctx.globalAlpha=1;ctx.beginPath();ctx.arc(head[0],head[1],isSelected?13:11,0,Math.PI*2);ctx.fillStyle='#c9eb86';ctx.fill();ctx.lineWidth=isSelected?3:2;ctx.strokeStyle='#12313d';ctx.stroke();ctx.fillStyle='#18353a';ctx.font='800 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(s.id),head[0],head[1]+.5);hits.push({id:s.id,x:head[0],y:head[1]})}
 let hp=project(hotel.p,73,C),hfoot=project(hotel.p,0,C);ctx.strokeStyle='#95dadd';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(hfoot[0],hfoot[1]);ctx.lineTo(hp[0],hp[1]);ctx.stroke();ctx.fillStyle='#95dadd';ctx.beginPath();ctx.roundRect(hp[0]-14,hp[1]-14,28,28,7);ctx.fill();ctx.fillStyle='#15313c';ctx.font='800 13px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('H',hp[0],hp[1]);hits.push({id:'hotel',x:hp[0],y:hp[1]});if(stage==='all'||stage==='2'){let label='十六浦索菲特';ctx.font='600 11px system-ui';let tw=ctx.measureText(label).width,x=Math.max(8,Math.min(W-tw-12,hp[0]+18)),y=Math.max(76,hp[1]-2);ctx.fillStyle='rgba(9,34,44,.89)';ctx.fillRect(x-4,y-14,tw+8,18);ctx.fillStyle='#c0edf0';ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillText(label,x,y)}
}
function schedule(){if(pending)return;pending=requestAnimationFrame(()=>{pending=0;draw()})}
function resize(){let r=canvas.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);W=r.width;H=r.height;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);draw()}
new ResizeObserver(resize).observe(canvas);
function reset(){zoom=1;angle=-.16;tilted=true;panX=panY=0;document.querySelector('[data-control="tilt"]').textContent='2D';draw()}
function select(id){selected=id;if(id==='hotel'){document.getElementById('route-detail').innerHTML='<div class="mini">酒店 · H 独立标记</div><h4>澳门十六浦索菲特酒店</h4><a target="_blank" rel="noreferrer" href="https://all.accor.com/hotel/6480/index.zh.shtml">查看酒店官方页面 ↗</a>'}else{let s=route.find(x=>x.id===id);if(!s)return;document.getElementById('route-detail').innerHTML=`<div class="mini">路线标记 ${String(s.id).padStart(2,'0')} / 20</div><h4>${s.name}</h4><div class="action-line"><button type="button" class="history-open" data-open-history="${s.id}" aria-label="阅读${s.name}的完整历史">阅读完整历史 ↗</button><a target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.name+' 澳门')}">实时地图 ↗</a></div>`;document.querySelector(`[data-route-id="${s.id}"]`)?.scrollIntoView({block:'nearest'})}document.querySelectorAll('.route-row').forEach(b=>b.classList.toggle('selected',b.dataset.routeId===String(id)));draw()}
const stageNames={1:'南段 · 内港与山城',2:'老城 · 世界遗产',3:'东段 · 新口岸'};
document.getElementById('route-list').innerHTML=route.map(s=>`<button type="button" class="route-row" data-route-id="${s.id}" aria-label="路线第 ${s.id} 站 ${s.name}，打开完整历史档案"><span class="route-no">${s.id}</span><span>${s.name}<small class="section-label">${stageNames[s.stage]}</small></span></button>`).join('');document.querySelectorAll('.route-row').forEach(b=>b.onclick=()=>{let s=route.find(x=>x.id===Number(b.dataset.routeId));openHistory(s.id)});
function setStage(v){stage=v;zoom=1;panX=panY=0;document.querySelectorAll('.stage-tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.stage===v);b.setAttribute('aria-selected',b.dataset.stage===v?'true':'false')});select(active()[0].id)}
document.querySelectorAll('.stage-tabs button').forEach(b=>b.onclick=()=>setStage(b.dataset.stage));document.querySelectorAll('.controls button').forEach(b=>b.onclick=()=>{switch(b.dataset.control){case'rotate':angle+=Math.PI/9;break;case'tilt':tilted=!tilted;b.textContent=tilted?'2D':'3D';break;case'minus':zoom=Math.max(.65,zoom/1.2);break;case'plus':zoom=Math.min(3,zoom*1.2);break;case'reset':reset();return}draw()});
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);let r=canvas.getBoundingClientRect();pointers.set(e.pointerId,{x:e.clientX-r.left,y:e.clientY-r.top});tap=pointers.size===1?{x:e.clientX-r.left,y:e.clientY-r.top,moved:false}:null;if(pointers.size>1)pinch=null});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;let r=canvas.getBoundingClientRect(),p={x:e.clientX-r.left,y:e.clientY-r.top},old=pointers.get(e.pointerId);pointers.set(e.pointerId,p);if(pointers.size===1){if(tap&&Math.hypot(p.x-tap.x,p.y-tap.y)>6)tap.moved=true;panX+=p.x-old.x;panY+=p.y-old.y;schedule()}else if(pointers.size===2){let a=[...pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),mid={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2};if(pinch){zoom=Math.max(.65,Math.min(3,zoom*dist/pinch.dist));panX+=mid.x-pinch.mid.x;panY+=mid.y-pinch.mid.y;schedule()}pinch={dist,mid}}});
function pointerEnd(e){if(!pointers.has(e.pointerId))return;pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;if(pointers.size===0&&tap&&!tap.moved){let r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,near=hits.map(h=>({...h,d:Math.hypot(h.x-x,h.y-y)})).sort((a,b)=>a.d-b.d)[0];if(near&&near.d<28){if(near.id==='hotel')select('hotel');else openHistory(near.id)}}tap=null}canvas.addEventListener('pointerup',pointerEnd);canvas.addEventListener('pointercancel',pointerEnd);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(3,zoom*(e.deltaY>0?.91:1.09)));schedule()},{passive:false});canvas.addEventListener('keydown',e=>{let handled=true;if(e.key==='ArrowLeft')panX+=25;else if(e.key==='ArrowRight')panX-=25;else if(e.key==='ArrowUp')panY+=25;else if(e.key==='ArrowDown')panY-=25;else if(e.key==='+'||e.key==='=')zoom=Math.min(3,zoom*1.18);else if(e.key==='-')zoom=Math.max(.65,zoom/1.18);else if(e.key.toLowerCase()==='r')reset();else handled=false;if(handled){e.preventDefault();draw()}});

const historyOverlay=document.getElementById('history-overlay');let historyOpenId=null,historyReturnFocus=null;
function renderHistory(id){const s=route[id-1];if(!s)return;historyOpenId=id;document.getElementById('history-kicker').textContent=`沿途档案 · ${String(id).padStart(2,'0')} / 20 · ${stageNames[s.stage]}`;document.getElementById('history-title').textContent=s.name;document.getElementById('history-era').textContent=s.era;document.getElementById('history-dek').textContent=s.dek;document.getElementById('history-prose').innerHTML=s.story.map(p=>`<p>${p}</p>`).join('');document.getElementById('history-source').innerHTML=`资料来源：<a href="${s.source}" target="_blank" rel="noreferrer">${s.sourceLabel} ↗</a><br>文字据资料整理；街道与现代酒店的沿革按各自来源表述。`;document.getElementById('history-count').textContent=`${String(id).padStart(2,'0')} / 20`;document.getElementById('history-prev').disabled=id===1;document.getElementById('history-next').disabled=id===20;document.getElementById('history-scroll').scrollTop=0}
function openHistory(id){const s=route[id-1];if(!s)return;const firstOpen=historyOverlay.hidden;if(firstOpen)historyReturnFocus=document.activeElement;if(stage!=='all'&&stage!==String(s.stage))setStage(String(s.stage));select(id);renderHistory(id);historyOverlay.hidden=false;document.body.classList.add('history-active');if(firstOpen)document.getElementById('history-close').focus()}
function closeHistory(){if(historyOverlay.hidden)return;historyOverlay.hidden=true;historyOpenId=null;document.body.classList.remove('history-active');historyReturnFocus?.focus?.()}
document.getElementById('history-close').onclick=closeHistory;
historyOverlay.addEventListener('click',e=>{if(e.target===historyOverlay)closeHistory()});
document.getElementById('history-prev').onclick=()=>{if(historyOpenId>1)openHistory(historyOpenId-1)};
document.getElementById('history-next').onclick=()=>{if(historyOpenId<20)openHistory(historyOpenId+1)};
document.getElementById('route-detail').addEventListener('click',e=>{const b=e.target.closest('[data-open-history]');if(b)openHistory(Number(b.dataset.openHistory))});
document.addEventListener('keydown',e=>{if(historyOverlay.hidden)return;if(e.key==='Escape'){e.preventDefault();closeHistory();return}if(e.key!=='Tab')return;const items=[...historyOverlay.querySelectorAll('button:not(:disabled),a[href]')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
select(1);
